### ISSUE TITLE
Problem setting image-url after initialization of the directive

### ISSUE THREAD

**Issue by acromm** [bcabanes/angular-image-cropper#19]
I'am getting this exception: "Cropper: No image url given." because I'am setting the image-url after the initialization of the directive. I'am requesting to a web service an object including the URL and binding the result to the image-url attribute but when the init() is called the exception is raised.

Is there a way to initialize the directive manually?

> Error: Cropper: No image url given.
    at new Cropper (http://localhost/web/app/bower_components/ng-image-cropper/dist/angular-image-cropper.js:87:12)
    at module.exports.angular.module.directive.controller.init (http://localhost/web/app/bower_components/ng-image-cropper/dist/angular-image-cropper.js:889:25)
    at module.exports.angular.module.directive.link (http://localhost/web/app/bower_components/ng-image-cropper/dist/angular-image-cropper.js:894:23)
    at http://localhost/web/app/bower_components/angular/angular.js:8211:44
    at invokeLinkFn (http://localhost/web/app/bower_components/angular/angular.js:8217:9)
    at nodeLinkFn (http://localhost/web/app/bower_components/angular/angular.js:7726:11)
    at compositeLinkFn (http://localhost/web/app/bower_components/angular/angular.js:7075:13)
    at publicLinkFn (http://localhost/web/app/bower_components/angular/angular.js:6954:30)
    at boundTranscludeFn (http://localhost/web/app/bower_components/angular/angular.js:7093:16)
    at controllersBoundTransclude (http://localhost/web/app/bower_components/angular/angular.js:7753:18)

**Comment by acromm** [comment]
As a workaround I changed the link function to this:

`	        'link': function (scope, element, attributes, controller) {
	            attributes.$observe('imageUrl', function (newValue) {
                    if (newValue) {
	                    controller.element = element[0];
	                    controller.init();
                    }
	            });
	        }`

I'am really new to AngularJS and directives but it works for now. Maybe there is a more clean solution.

**Comment by bcabanes** [comment]
Hi @acromm,
The directive has to have the image url to initialize the cropper UI and set all the dimensions, calculate ratio... etc.

You can just put an ngif on the directive waiting that your `image-url` is not undefined. When it will be defined, it will initiate the directive and should not throw error.

Edit:
It seems that we respond at the same time! ✨

**Comment by acromm** [comment]
oh, that's a good one there using ng-if. What do you think about my solution? Is ng-if more efficient?

**Comment by bcabanes** [comment]
Hum, your solution works but is kinda really complex for a simple behaviour. Prefer Ngif, you will see immediately what you code do just by looking at it. You'll have more control.

**Comment by acromm** [comment]
Ok Benjamin, thanks a lot for your help.
